### ISSUE TITLE
Top Summary Does not Load (For a month selection in date filter)

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#144]
The top summary does not load if the month is selected from the same year
https://ka.staging.ilp.org.in/gka/#datemodal?boundary_id=424&from=2018-01-01&to=2018-02-28

@ansal @shivangi

**Comment by shivangi** [comment]
@ansal this must be the same issue as the boundary change also not being updated. Can you check your code for capturing these changes and loading the top summary?

**Comment by ansal** [comment]
@shivangi I have made the year parameter as "to" year - 1 + "to year".

**Comment by shivangi** [comment]
Its work. 
@menakakhare please test.
