### ISSUE TITLE
Checking the counts on GKA Dashboard

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#148]
https://docs.google.com/spreadsheets/d/1RfLkYHs0qXTqMwbZcSt1pu11Q7KDngUImeETVXIoPLU/edit#gid=37431170

@ansal @shivangi @ShwetanshuSingh

**Comment by shivangi** [comment]
@ShwetanshuSingh these were resolved right? If there is any further mismatch can you please point it here in the ticket? Give the section information here. The sheet is not updated.
