### ISSUE TITLE
Some Images do not load in "More Info" tab

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#149]
https://dev.ilp.org.in/school/33316/#?tab=info

tagging this issue: @subhaklp 

@brijeshpoojary @shivangi @ansal

**Comment by menakakhare** [comment]
Images are still not loading.
Link:-
https://dev.ilp.org.in/school/32205/#?tab=info
https://ka.staging.ilp.org.in/school/32211/#?tab=info

**Comment by menakakhare** [comment]
@chiraganand The image loading problem still persists .

CC @subhaklp

**Comment by subhaklp** [comment]
@menakakhare This is also a nginx config issue. @chiraganand what's going on?

**Comment by chiraganand** [comment]
This is related to #154. As request URIs have changed from KLP app, we need to know what all paths the app is requesting before nginx config can be finalised. @ansal is looking into it.

**Comment by chiraganand** [comment]
This is fixed now.

**Comment by menakakhare** [comment]
Reviewed .
