### ISSUE TITLE
"Compare To" fails for few school selections

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#150]
![screen shot 2018-02-27 at 11 13 46 pm](https://user-images.githubusercontent.com/30497144/36744907-035950de-1c14-11e8-9f94-7a10023c4983.png)
Assigning : @subhaklp 

CC: @shivangi @ansal

**Comment by subhaklp** [comment]
@menakakhare are you referring to a problem with the search where its not finding relevant schools?

**Comment by menakakhare** [comment]
Reviewed
