### ISSUE TITLE
Data page throws errors on clicking download

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#154]
Link : https://dev.ilp.org.in/media/school-data/primaryschool.csv

On clicking download after taking credential the page throws an error.

Assigning to : @subhaklp 
CC : @shivangi @ansal

**Comment by subhaklp** [comment]
Chirag has completed adding files to the /media directory. We are done here.

**Comment by menakakhare** [comment]
@subhaklp : Yet to be fixed

It works on dev but not on Staging
https://dev.ilp.org.in/data/
https://ka.staging.ilp.org.in/media/school-data/primaryschool.csv

**Comment by subhaklp** [comment]
It is a Nginx config issue which @chiragklp needs to fix.

**Comment by chiraganand** [comment]
@ansal is looking into it, will update when we have a fix.

**Comment by chiraganand** [comment]
Both are now working:
https://ka.staging.ilp.org.in/media/school-data/primaryschool.csv
https://dev.ilp.org.in/media/school-data/primaryschool.csv

**Comment by menakakhare** [comment]
![screen shot 2018-03-27 at 10 17 36 pm](https://user-images.githubusercontent.com/30497144/37982242-b33dff9a-320d-11e8-80aa-a82d3940e4cf.png)
 @chiraganand it gives an error when you click on Data page.

On dev also it gives error.
https://dev.ilp.org.in/data/

**Comment by menakakhare** [comment]
![screen shot 2018-03-27 at 10 25 47 pm](https://user-images.githubusercontent.com/30497144/37982323-e78f311a-320d-11e8-859d-2eda9e824564.png)

**Comment by chiragklp** [comment]
This is fixed by @subhaklp it is now working.

**Comment by menakakhare** [comment]
Tested, works !
