### ISSUE TITLE
GKA Dashboard Top Summary is not changing as per Filter selection 

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#155]
@ansal @nabeelvalapra

**Comment by shivangi** [comment]
@ansal can you check if the haschange event is being captured and the surveys/tagmappingsummary and survey/summary is being called with the new boundary. I cannot see it being called in the network calls.

**Comment by ansal** [comment]
@shivangi Yes the hash changes are captured and passed on to the endpoints. Here are the urls being called when Bengaluru Rural district is selected - 

https://dev.ilp.org.in/api/v1/surveys/tagmappingsummary/?survey_tag=gka&boundary_id=433&from=2017-06-01&to=2018-03-31&year=1718&state=ka
https://dev.ilp.org.in/api/v1/surveys/usercount/?survey_tag=gka&boundary_id=433&from=2017-06-01&to=2018-03-31&state=ka

**Comment by shivangi** [comment]
@ShwetanshuSingh please test this.

**Comment by ShwetanshuSingh** [comment]
@shivangi the numbers for the boundary filter end point shared above seem fine, however, the active users has to be integrated as a a parameter within it too using the **assesssments_answergroup_institution** as a bridge table

here's an example - for the district of gadag for this academic year:
`ilp=> select count(distinct uu.id) 
from users_user uu
join assessments_answergroup_institution aai
on uu.id = aai.created_by_id
join schools_institution si
on si.id = aai.institution_id
where date_of_visit > '2017-06-01'
and si.admin1_id = 420;
 count 
-------
   238`

**Comment by shivangi** [comment]
@nabeelvalapra can you look at this one? You will have to add filter for boundary(if not passed then state) and institution to the SurveyUsersCountAPIView.

**Comment by menakakhare** [comment]
Reviewed , Raising a new bug for Chamrajnagar filter selection failing for survey responses.
