### ISSUE TITLE
GKA Monitoring: not all user mappings being migrated from stories_story to UnifyDB

### ISSUE THREAD

**Issue by ShwetanshuSingh** [klpdotorg/ilp#157]
@shivangi 
```
Select count(aai.id)                                 
From assessments_answergroup_institution aai
where questiongroup_id in (17, 24)
and date_of_visit > '2017-07-01' and aai.created_by_id is null;
 count 
-----------
  1607

dubdubdub=> select user_id from stories_story where id = '415539';
 user_id 
-------------
      56

ilp=> select created_by_id from assessments_answergroup_institution where id = '415539';
 created_by_id
--------------

**Comment by shivangi** [comment]
@ShwetanshuSingh the assessment is there:-
   id   | group_value |     date_of_visit      | comments | is_verified | sysid |          entered_at           | created_by_id | institution_id | questiongroup_id | status_id | respondent_type_id | location | mobile 
--------+-------------+------------------------+----------+-------------+-------+-------------------------------+---------------+----------------+------------------+-----------+--------------------+----------+--------
 415539 |             | 2017-07-06 08:48:23+00 |          | t           |       | 2017-07-06 15:00:08.275903+00 |               |          24009 |               17 | AC        | AS                 |          | 
(1 row)

**Comment by ShwetanshuSingh** [comment]
I never meant to state that the entry isn't there. The createdby_id is the field that is missing from the assessment entry despite the fact that there's an associated user_id in dubdubdub.

**Comment by shivangi** [comment]
@ShwetanshuSingh ok this is the case when there were multiple mobiles associated with the user and both those mobiles were already present in the db so no entry was made for that user.

**Comment by ShwetanshuSingh** [comment]
but that leaves the survey unmapped to the user right?

there's a large number of these too ~1600
