### ISSUE TITLE
Need to add a Hyphen "-"

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#159]
Need to add a hyphen for the Source : KLP Database 17-18

![screen shot 2018-03-02 at 1 08 02 pm](https://user-images.githubusercontent.com/30497144/36888459-90dabc8c-1e1b-11e8-8066-c5b8f13d6fa9.png)

Assigned to : @subhaklp 
@ansal

**Comment by menakakhare** [comment]
@subhaklp : Yet to be fixed

https://ka.staging.ilp.org.in/school/32205/#?tab=info
https://dev.ilp.org.in/school/32211/#?tab=programmes

**Comment by subhaklp** [comment]
Fixed

**Comment by menakakhare** [comment]
Reviewed.
