### ISSUE TITLE
Verify accuracy in counts for Konnect "Report Generation"

### ISSUE THREAD

**Issue by ansal** [klpdotorg/ilp#166]

**Comment by shivangi** [comment]
@ansal @ShwetanshuSingh can you give me more information on which counts are not correct or should be checked so i can look into it?

**Comment by ShwetanshuSingh** [comment]
@shivangi 

So I spotted a couple of issues in the json response for this API end-point. There's the known issue of the dummy community survey questions being included in the response. Besides that, the numbers seem to be significantly off.

for example, for https://dev.ilp.org.in/api/v1/surveys/questiongroupdetails/?questiongroup_id=24&from=2017-07-01&to=2018-03-31

the numbers in the response for one of the questions are:
`"Did you observe the math class happening in class 4 or 5 at the time of your visit?": {
"Yes": 1231,
"text": "Did you observe the math class happening in class 4 or 5 at the time of your visit?",
"No": 202,
"Don't Know": 3,
"id": 302
}`

whereas, the numbers in the DB are as follows:
`ilp=> select aa.answer, count(*)
from assessments_answergroup_institution aai
Left outer join assessments_answerinstitution aa
On aai.id = aa.answergroup_id
where aai.questiongroup_id in (24)
and aai.date_of_visit > '2017-06-01'
And aa.question_id in (131, 302) group by aa.answer;
   answer   | count 
------------+-------
 Don't Know |     5
 No         |  1318
 Yes        |  3776`

**Comment by shivangi** [comment]
@ShwetanshuSingh can you test this?

**Comment by shivangi** [comment]
@ansal did the Konnect app add the survey_tag filter? 
@ShwetanshuSingh @ansal test and close this issue.

**Comment by ShwetanshuSingh** [comment]
the numbers in the json are still off and the known issue of the dummy community survey questions being included in the response still persists.

**Comment by ansal** [comment]
@ShwetanshuSingh Should we close this one as we have another issue for the same here - https://github.com/klpdotorg/ilp/issues/194
