### ISSUE TITLE
Mapping a survey to a state and user type

### ISSUE THREAD

**Issue by ansal** [klpdotorg/ilp#167]
A survey belongs to a state and multiple user types. We need this relation in our models and endpoints.

This helps Konnect to filter surveys that belong to a particular state and/or user type.

**Comment by ansal** [comment]
@menakakhare The state is already mapped to the survey (as a foreign key id in the survey table).

@shivangi We need to do the usertype mapping.

**Comment by shivangi** [comment]
@ansal there is just one survey associated with konnect, no?
@menakakhare can you give me the usecase for this requirement? also do for user type mapping, do we have information for which user types are to be mapped to which surveys?

**Comment by ansal** [comment]
> @ansal there is just one survey associated with konnect, no?
@shivangi No. At present there are two surveys. And we will be adding more surveys in the future.
