### ISSUE TITLE
Add new GKA Monitoring question group for 2018-19 academic year

### ISSUE THREAD

**Issue by ansal** [klpdotorg/ilp#168]

**Comment by menakakhare** [comment]
List of question for the academic year 2018-19 (All the following questions have response as Yes or No as radio button for selection)
1. Was the Math class happening at the time of your visit ?
2. Was the teacher teaching trained in GKA methodology? 
3. Did you observe the GKA TLM being used during the class?
4. Did you see representational stage being practiced during the class?
5. Did you see group work happening?

Apart, from the above 5 questions we need to include Comment and Photo upload option for each survey response.

I think there is already a question group with the same set of above questions.

**Comment by shivangi** [comment]
@ansal @menakakhare cant we use the existing question group?

**Comment by menakakhare** [comment]
@ansal I think we decided to use the existing question group since there was no change in the questions.
