### ISSUE TITLE
Include a field in survey to identify if a grade selection is necessary before user submits the response

### ISSUE THREAD

**Issue by ansal** [klpdotorg/ilp#170]

**Comment by shivangi** [comment]
@ansal we have a column called group_text in questiongroup table. This is set to "child_name" for GP contest. Can we use it for this purpose and set it to "grade"?

**Comment by shivangi** [comment]
Also again in this case too, if we are doing assessment on student we are doing mapping to grade/class and if we are doing assessment on class we anyways are doing mapping to class. I am little confused about this usecase.

**Comment by ansal** [comment]
> @ansal we have a column called group_text in questiongroup table. This is set to "child_name" for GP contest. Can we use it for this purpose and set it to "grade"?

If `group_text` is used for something else, I think we better create a boolean field for indication if grade selection is mandatory or not.

> Also again in this case too, if we are doing assessment on student we are doing mapping to grade/class and if we are doing assessment on class we anyways are doing mapping to class. I am little confused about this usecase.

We are doing assessments on Institutions no? I mean Konnect creates records on `AnswerGroup_Institution` right? So we need the mapping to a class.

@menakakhare Can you give us more info about why we need this mapping?

**Comment by menakakhare** [comment]
Grade selection is relevant for GKA Monitoring Survey and the upcoming Teacher's Survey.

Use case: We want to know the GKA monitoring survey happened for which grade and the same is applicable for Teacher's survey as to the kit is being used for which grades.

**Comment by shivangi** [comment]
@ansal this is done. Close it once you verify it.
