### ISSUE TITLE
Review Import scripts for GP Contest and HH Survey

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#172]
Review scripts

Import Script for GP Contest
--
Import Scripts for HH Survey Data

**Comment by brijeshpoojary** [comment]
@shivangi  Attaching the scripts for importing gp contest data and house hold survey data to unified db.

[import_gp_contest.zip](https://github.com/klpdotorg/ilp/files/1787838/import_gp_contest.zip)
[import_house_hold_survey.zip](https://github.com/klpdotorg/ilp/files/1787839/import_house_hold_survey.zip)

**Comment by shivangi** [comment]
Reviewed
