### ISSUE TITLE
Create Kit Usage Survey (for Teachers)

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#175]
1. Which Grade(s) you teach - multiple selection box (grade 1 to 8 )
2. Do you use the GKA math kit TLMs in your math class? (Yes or No)
3. Is the Math kit helpful in improving learning outcome in math? (Yes or No)
4. Which TLM is most liked by the students (drop down box - chose 1)
5. How do you rate the math kit contents? (MCQ) [Extremely Satisfied - Satisfied - Neither Satisfied nor Dissatisfied - Dissatisfied - Extremely DIssatisfied]
6. Please upload a photo of how you use the math kit or any innovation/improvisation in the math kit that you adopt while teaching? (optional)

**Comment by shivangi** [comment]
@ansal this is over, right? Can you close it?
