### ISSUE TITLE
Label Change on GKA Dashboard

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#178]
![screen shot 2018-03-08 at 11 28 35 am](https://user-images.githubusercontent.com/30497144/37136306-0c8f4f1e-22c7-11e8-87b7-08e721c48ea9.png)

I will send more changes post lunch.

**Comment by menakakhare** [comment]
![screen shot 2018-03-08 at 2 15 42 pm](https://user-images.githubusercontent.com/30497144/37141929-9f690edc-22dc-11e8-94ab-5e2420b999af.png)
![screen shot 2018-03-08 at 2 13 12 pm](https://user-images.githubusercontent.com/30497144/37141936-a2932a52-22dc-11e8-8186-39f88fe662d4.png)
![screen shot 2018-03-08 at 2 11 17 pm](https://user-images.githubusercontent.com/30497144/37141959-acecc86e-22dc-11e8-91aa-464978d5c6ae.png)
![screen shot 2018-03-08 at 2 20 59 pm](https://user-images.githubusercontent.com/30497144/37141964-b079efb6-22dc-11e8-9ce9-43a767bb4647.png)

**Comment by menakakhare** [comment]
![screen shot 2018-03-08 at 8 57 25 pm](https://user-images.githubusercontent.com/30497144/37160751-f087ba18-2316-11e8-9a0b-19ebbaee7b21.png)

**Comment by menakakhare** [comment]
![screen shot 2018-03-08 at 9 36 28 pm](https://user-images.githubusercontent.com/30497144/37161560-09614c46-2319-11e8-9638-6a208069ae95.png)

**Comment by ShwetanshuSingh** [comment]
@ansal 

The Survey Respondents graph has overlapping x-axis labels, do you think these could be replaced with the abbreviations as you have done in the Monitoring Volumes graph?

**Comment by ansal** [comment]
@ShwetanshuSingh That can be done.

**Comment by menakakhare** [comment]
![screen shot 2018-03-12 at 9 13 58 pm](https://user-images.githubusercontent.com/30497144/37293890-959d6d74-263a-11e8-91b0-e169e50d3fd0.png)

**Comment by ShwetanshuSingh** [comment]
@ansal Here are the initial list of minor changes to be made to the Dashboard:

- make all label texts straight and not oblique
- replace the orange color in the GKA Monitoring Summary > Monitoring Responses > GKA Methodology  to grey. These bars have the vacant part in orange color whereas everywhere it is grey.

**Comment by menakakhare** [comment]
@ansal 

Few more minor changes:- 
![screen shot 2018-03-21 at 11 44 41 am](https://user-images.githubusercontent.com/30497144/37697147-27e27ba8-2d01-11e8-83db-113cf54b9bba.png)

**Comment by menakakhare** [comment]
![screen shot 2018-03-21 at 12 08 59 pm](https://user-images.githubusercontent.com/30497144/37697256-c9aed792-2d01-11e8-9c0b-eb93d7536f69.png)

**Comment by menakakhare** [comment]
Problems when dashboard is viewed on mobile:-
![screen shot 2018-03-21 at 9 46 46 pm](https://user-images.githubusercontent.com/30497144/37722214-72c7d9e2-2d51-11e8-9eea-dd6269a4b135.png)

**Comment by menakakhare** [comment]
@ansal I think most of the escalations are addressed. I was unable to check the monitoring section as the graphs are not loading in dev.

**Comment by menakakhare** [comment]
Reviewed
