### ISSUE TITLE
"District selection" in Filters does not work for GP Contest

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#181]
![screen shot 2018-03-13 at 6 48 17 am](https://user-images.githubusercontent.com/30497144/37317589-c049ab2c-268b-11e8-8b52-9364662d77dc.png)

In GP Contest section, "GP Covered" always shows the total no of GPs instead of showing the count of GPs within the District as per selection. Other filter selection such as block/cluster and school does not apply for "GP Covered" as a GP is larger boundary than a cluster/school. When a user applies filter for block/cluster/school lets show the total GPs covered in that particular district.

**Comment by shivangi** [comment]
@nabeelvalapra please have a look at this.

**Comment by shivangi** [comment]
Fixed.
