### ISSUE TITLE
Make GKA Dashboard Filter Buttons More Descriptive

### ISSUE THREAD

**Issue by ShwetanshuSingh** [klpdotorg/ilp#184]
- Keep drop-down filters (District, Block, Cluster, Schools) as the first row
- Shift buttons to second row and make them more descriptive by adding text with the icons
     - Generate Report + "search icon"
     - Reset + "reset icon"
     - Select Date Range + "calendar icon"

**Comment by menakakhare** [comment]
![screen shot 2018-03-14 at 1 30 31 pm](https://user-images.githubusercontent.com/30497144/37390229-419845ba-278d-11e8-9578-7a56aab98a8f.png)
