### ISSUE TITLE
GKA Dashboard: Survey Responses Empty for District Filter Selection Chamarajnagara

### ISSUE THREAD

**Issue by ShwetanshuSingh** [klpdotorg/ilp#193]
https://ka.staging.ilp.org.in/api/v1/survey/detail/source/?survey_tag=gka&survey_id=7&boundary_id=439&from=2017-06-01&to=2018-03-31&state=ka

**Comment by ansal** [comment]
@ShwetanshuSingh @menakakhare This is fixed.

**Comment by menakakhare** [comment]
Reviewed .
