### ISSUE TITLE
DISE option under Reports on both Staging and Dev redirects to Production DISE app

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#198]
Production : https://dise.klp.org.in/
dev: https://dise.dev.ilp.org.in/
staging: https://dise.staging.ilp.org.in/

**Comment by subhaklp** [comment]
Fixed

**Comment by menakakhare** [comment]
@subhaklp Staging point to https://dise.dev.ilp.org.in/ instead of https://dise.staging.ilp.org.in/

**Comment by subhaklp** [comment]
@chiraganand can you please comment on this?

**Comment by chiraganand** [comment]
Yes, this is fixed now.

**Comment by menakakhare** [comment]
Reviewed.
