### ISSUE TITLE
Filter selection for block does not clear on changing the District

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#200]
![screen shot 2018-03-21 at 4 44 22 pm](https://user-images.githubusercontent.com/30497144/37707010-7cf3649c-2d27-11e8-9d84-d6d7635c4c36.png)
![screen shot 2018-03-21 at 4 44 45 pm](https://user-images.githubusercontent.com/30497144/37707012-7ef98a32-2d27-11e8-81a8-6d23da1adc9a.png)

**Comment by menakakhare** [comment]
It affects school selection as well.

**Comment by ansal** [comment]
@menakakhare Fixed.

**Comment by menakakhare** [comment]
Fixed on Dev
