### ISSUE TITLE
Remove % value from GKA Dashboard

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#201]
![screen shot 2018-03-21 at 5 01 01 pm](https://user-images.githubusercontent.com/30497144/37707582-9a228ce4-2d29-11e8-9dc4-2a93e7f6a138.png)
![screen shot 2018-03-21 at 5 02 48 pm](https://user-images.githubusercontent.com/30497144/37707635-d5ce800e-2d29-11e8-8d32-7c90a72c3091.png)
 

The % Values are not coming out right. We are getting values more than 100% . Please remove this parameter from the dashboard.

**Comment by shivangi** [comment]
@menakakhare can you give information about the boundary for which this error occurred?

**Comment by ansal** [comment]
@menakakhare Fixed.

**Comment by menakakhare** [comment]
Fixed on Dev.
