### ISSUE TITLE
Koppal District shows up twice

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#202]
![screen shot 2018-03-21 at 5 06 45 pm](https://user-images.githubusercontent.com/30497144/37707818-71a0a02a-2d2a-11e8-9af2-5596c47f4f31.png)

Please check the Bangalore District options as well.

**Comment by menakakhare** [comment]
![screen shot 2018-03-21 at 5 09 45 pm](https://user-images.githubusercontent.com/30497144/37707874-a6b88a34-2d2a-11e8-8234-b19c85c0c1b6.png)

**Comment by shivangi** [comment]
@menakakhare The community survey was conducted in pre and primary schools. So one koppal is the primary district boundary and other koppal is the preschool district boundary. 
So both are valid (they have different ids).

**Comment by menakakhare** [comment]
@shivangi Pre-schools do not come under GKA. We should be only be showing Primary school boundaries in the dashboard.

**Comment by shivangi** [comment]
@menakakhare can you verify and close this?

**Comment by menakakhare** [comment]
Reviewed
