### ISSUE TITLE
Date range selection : across two academic year

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#203]
The counts returned are not accurate when the data range selection is across two academic year

https://ka.staging.ilp.org.in/gka/#searchmodal?boundary_id=445 (2016-2018)
https://ka.staging.ilp.org.in/gka/#datemodal?boundary_id=445&from=2016-01-01&to=2017-03-31 (2016-2017)

Refer to counts under assessment section.

**Comment by shivangi** [comment]
@menakakhare the counts is 0 under assessments section as that boundary does not have any GKA assessments.

SO its not a bug.

**Comment by menakakhare** [comment]
https://ka.staging.ilp.org.in/gka/#datemodal?from=2016-03-01&to=2017-03-31

2016-2017
![screen shot 2018-03-22 at 12 29 23 pm](https://user- images.githubusercontent.com/30497144/37755736-ae8392f2-2dcc-11e8-8869-4ab3db990a37.png)

2016-2018
https://ka.staging.ilp.org.in/gka/#searchmodal?boundary_id=418
![screen shot 2018-03-22 at 12 31 31 pm](https://user-images.githubusercontent.com/30497144/37755821-11ccaf6a-2dcd-11e8-800f-ffc1f52a6ec5.png)

**Comment by menakakhare** [comment]
![screen shot 2018-03-22 at 12 29 23 pm](https://user-images.githubusercontent.com/30497144/37755840-26e2865e-2dcd-11e8-9531-5bdf1650820d.png)
 (2016 - 2017 : we get data)

**Comment by menakakhare** [comment]
This Works ! The default value in Date filter is causing confusion. Will raise a new issue for this.
