### ISSUE TITLE
Competency Graphs labels gets cluttered for Phase 1 Districts in Assessment Section

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#204]
Phase 2 District (Gadag) : Labels on graph are spaced out well
https://ka.staging.ilp.org.in/gka/#searchmodal?boundary_id=420
![screen shot 2018-03-22 at 12 15 29 pm](https://user-images.githubusercontent.com/30497144/37755272-d0508eaa-2dca-11e8-9628-00434dc6fad5.png)

Phase 1 Districts (Raichur) : Labels are crowded
https://ka.staging.ilp.org.in/gka/#datemodal?boundary_id=418&from=2016-01-01&to=2017-03-31

![screen shot 2018-03-22 at 12 17 49 pm](https://user-images.githubusercontent.com/30497144/37755327-0fe3756e-2dcb-11e8-991d-4b47c4d44e40.png)

Another Phase 1 example : 
https://ka.staging.ilp.org.in/gka/#datemodal?boundary_id=416&from=2016-01-01&to=2017-03-31

**Comment by menakakhare** [comment]
This needs to be fixed still.

**Comment by ansal** [comment]
@menakakhare Fixed.

**Comment by menakakhare** [comment]
Reviewed.
