### ISSUE TITLE
Date Filter creates confusion while Generating Report

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#206]
Program team members are getting confused between the "Apply Date Filter" and "Generate Report" Option. Please use the design below :
![screen shot 2018-03-22 at 4 34 26 pm](https://user-images.githubusercontent.com/30497144/37767420-1b39ad96-2df0-11e8-941b-dcd194032942.png)

**Comment by menakakhare** [comment]
![screen shot 2018-03-22 at 4 34 26 pm](https://user-images.githubusercontent.com/30497144/37767571-8bca9908-2df0-11e8-9f5b-0e9e2e5dbd95.png)

**Comment by menakakhare** [comment]
Also, when a user changes the date range the report should show the values only upon clicking "Generate Report"

**Comment by ansal** [comment]
@menakakhare So we are getting rid of the date select popup modal, right?

**Comment by menakakhare** [comment]
Yes we want reports to be generated only on clicking "Generate Report". We do not want the date select pop up, its causing confusion as that also generates report.

**Comment by menakakhare** [comment]
Reviewed.
