### ISSUE TITLE
Top Search in School Map not working

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#207]
![screen shot 2018-03-23 at 10 51 39 am](https://user-images.githubusercontent.com/30497144/37812895-7e335512-2e88-11e8-99d5-2331412997c8.png)
https://ka.staging.ilp.org.in/map/#15/13.00991/77.65705

**Comment by subhaklp** [comment]
Merged into master. Ready for test.

**Comment by menakakhare** [comment]
![screen shot 2018-03-27 at 10 17 36 pm](https://user-images.githubusercontent.com/30497144/37981971-bc6f4d4a-320c-11e8-8df5-12c733f01055.png)
I still see the issue.

**Comment by menakakhare** [comment]
Works on dev but not on staging. @subhaklp / @shivangi should we close this bug.

**Comment by menakakhare** [comment]
Reviewed.
