### ISSUE TITLE
Incorrect Values in "More Info" of Boundary page 

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#208]
Dev: 
https://dev.ilp.org.in/primary-district/418/
![screen shot 2018-03-23 at 11 24 56 am](https://user-images.githubusercontent.com/30497144/37813845-2a6e351e-2e8d-11e8-8b3f-78af3a172b69.png)

Prod: 
https://klp.org.in/primary-district/418/#2014-2015

![screen shot 2018-03-23 at 11 27 37 am](https://user-images.githubusercontent.com/30497144/37813856-3aa6570e-2e8d-11e8-8e57-a9997beccd5c.png)

Staging: Does not load info
https://ka.staging.ilp.org.in/primary-district/420/

**Comment by subhaklp** [comment]
Just fixed it.

**Comment by menakakhare** [comment]
Reviewed.
