### ISSUE TITLE
Boundary Page: "More Info" tab does not show complete info for District/Block /Cluster/ Project /Circle

### ISSUE THREAD

**Issue by menakakhare** [klpdotorg/ilp#211]
Example links:
Dev:
https://dev.ilp.org.in/project/9116/
https://dev.ilp.org.in/cluster/3253/
https://dev.ilp.org.in/circle/8855/
https://dev.ilp.org.in/block/592/

**Comment by subhaklp** [comment]
@menakakhare you mean there's no programmes info in here? That's the only error I saw int he UI. What else is missing?

**Comment by menakakhare** [comment]
I think mostly its working fine. But the date source is missing.

https://ka.staging.ilp.org.in/block/596/
![screen shot 2018-03-26 at 2 37 18 pm](https://user-images.githubusercontent.com/30497144/37897389-b577f546-3103-11e8-9290-04c8301b67d6.png)

**Comment by subhaklp** [comment]
@menakakhare I've fixed the "B" or "D" icon inside the circle before the boundary name at hte top of the page. This was missing only for preschool districts. I can't seem to fix this dropdown for the year. I think @awesomepankaj might be able to quickly look into this one.

**Comment by menakakhare** [comment]
@awesomepankaj Can you look into this issue.
