### ISSUE TITLE
GKA Dashboard: GP Count off from UnifyDB

### ISSUE THREAD

**Issue by ShwetanshuSingh** [klpdotorg/ilp#212]
the count on UnifyDB is retrieved using the following query

> select count(distinct si.gp_id) 
> from assessments_answergroup_institution aai 
> join schools_institution si 
> on aai.institution_id = si.id 
> where questiongroup_id in (21,22,23) 
> and date_of_visit >  '2017-07-01';

and comes to 328, whereas the current dashboard count is 344

**Comment by shivangi** [comment]
@ShwetanshuSingh If a gp contest happens in a place in 2 separate months it will get counted twice. So thats why there is the number mis match. I had specified this before as well.
@menakakhare

**Comment by menakakhare** [comment]
@shivangi , Its correct to count the a GP twice if the contest has happened in the same GP in two different months. However, the possibility of GP contest happening twice in the same academic year is not possible. A GP conducts the contest only once in a academic year. So I doubt if the additional no we are seeing is due to that.

**Comment by shivangi** [comment]
@ShwetanshuSingh : it does have:-
ilp=> select distinct s.gp_id, count(distinct to_char(date_of_visit,'YYYYMM')) from assessments_answergroup_institution ag, schools_institution s where ag.institution_id=s.id and ag.questiongroup_id in (select id from assessments_questiongroup where survey_id =2) and  date_of_visit > '2017-07-01' group by s.gp_id having count(distinct to_char(date_of_visit,'YYYYMM'))>1;
 gp_id | count 
-------+-------
  4167 |     2
  1446 |     2
  4172 |     2
  3986 |     2
  3984 |     2
  1042 |     2
  2118 |     2
  1744 |     2
  5174 |     2
  3768 |     2
  6105 |     2
  1591 |     2
  4670 |     2
   801 |     2
  4174 |     2
       |     4
  1806 |     2
(17 rows)

ilp=> select distinct to_char(date_of_visit,'YYYYMM') from assessments_answergroup_institution ag, schools_institution s where ag.institution_id=s.id and ag.questiongroup_id in (select id from assessments_questiongroup where survey_id =2) and  date_of_visit > '2017-07-01' and s.gp_id=4167;
 to_char 
---------
 201709
 201711
(2 rows)
