### ISSUE TITLE
Accessing student groups a student belongs to returns wrong 'status' field.

### ISSUE THREAD

**Issue by subhaklp** [klpdotorg/ilp#30]
There's a URL pattern like below:

/students/id/studentgroups/

that's handled by the StudentGroupViewSet. The JSOn this URL returns has status as 'AC' for all the studentgroups that this student belongs to. This is because the 'status' field is being returned from student group model and not the student_studentgroup relation model. We should use the latter's status for this particular query. Need to fix.

**Comment by harisibrahimkv** [comment]
@subhaklp You can change that in the corresponding serializer.
